directories:
  "test":
    IrresponsibleModule:
      enabled: false
    UtilityFunction:
      enabled: false
  "scripts":
    IrresponsibleModule:
      enabled: false
    UtilityFunction:
      enabled: false
