directories:
  "test":
    IrresponsibleModule:
      enabled: false
    UtilityFunction:
      enabled: false
  "script":
    IrresponsibleModule:
      enabled: false
    UtilityFunction:
      enabled: false
