# Load Rubocop plugins.
require:
  - rubocop-rake
  - rubocop-minitest
  - rubocop-performance

inherit_gem:
  gemwork: lib/rubocop/.rubocop-gems.yml

AllCops:
  TargetRubyVersion: 3.2

Performance/OpenStruct:
  Enabled: false # Reconsider later.
