# Load Rubocop plugins.
plugins:
  - rubocop-rake
  - rubocop-minitest
  - rubocop-performance

inherit_gem:
  gemwork: lib/rubocop/.rubocop-gems.yml

AllCops:
  TargetRubyVersion: 3.2

Naming/MethodParameterName:
  AllowedNames:
    - id
